config/routes.rb
SampleApp::Application.routes.draw do  

  get '/pages/index' => redirect('/pages')
  
  resources :sessions, :only => [:new, :create, :destroy] do 
    collection do
      post :fb_signin
    end
  end
  
  resources :users do
    member do
      post :fb_unlink
      get :following, :followers       #makes users/1/following and following_user_path
    end
    collection do
      post :send_password_recovery
      get :password_recovery
      get :activate
      get :send_activation
      post :create_fb
      get :new_fb
    end
  end

  resources :pages

  resources :tokens, :only => [:create, :index, :destroy] do
    collection do
      put :refresh
      get :logout, to: 'tokens#destroy'
    end
  end

  resources :games

  put '/games/:game_id/winner/:user_id', to: 'games#winner'

  root :to => "pages#home" 
  get '/signup', :to => 'users#new'
  get '/contact', :to => 'pages#contact'
  get '/about', :to => 'pages#about'
  get '/signin', :to => 'sessions#new'
  get '/signout', :to => 'sessions#destroy'
  get '/admin', :to => 'pages#admin'
  get '/maintenance', :to => 'pages#maintenance'
  get '/error', :to => 'pages#error'
  get '/sitemap', :to => 'pages#site_map'
  get '/sitemap_xml', :to => 'pages#site_map_xml'

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_protected

  belongs_to :player1, :class_name => "User"
  belongs_to :player2, :class_name => "User"
  belongs_to :winner,  :class_name => "User"
  belongs_to :loser,  :class_name => "User"

  validates :player1_id, :presence => true
  validates :player2_id, :presence => true

  def name

    result = ""
    if player1
      result = player1.name
    end

    result = result + " vs "
    if player1
      result = result + player2.name
    end

    result
  end

  def winner_name
    if(winner)
      winner.name

    else
      "No Winner"
    end
  end

  def for_user_id user_id
    where("player1 = #{user_id} OR player2 = #{user_id}")
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def new
    @object = Game.new

    @users = User.all
    @players = @users
  end

  def create

    @object = Game.new(get_request_as_json params, :game)

    @users = User.all
    @players = @users

    if @object.winner
      if @object.winner == @object.player1
        @object.loser = @object.player2
      end
    end

    if @object.save

      respond_to do |format|
        format.html  {redirect_to @object}
        format.json  { render :json => @object }
      end

    else
      respond_to do |format|
        format.html  {render 'new'}
        format.json  { render :json => {:result => "Error"} }
      end
    end
  end

  def show
    @title = 'Details'
    id = params[:id]
    @object = Game.find(id)

    respond_to do |format|
      format.html  #normal flow
      format.json  { render :json => @object}
    end

  end

  def edit

    @users = User.all
    @players = @users

    @title = "Edit"
    @object = Game.find(id = params[:id])

    respond_to do |format|
      format.html  #normal flow
      format.json  { render :json => @object }
    end
  end

  def update
    @object = Game.find(params[:id])

    @users = User.all
    @players = @users

    if @object.winner
      if @object.winner == @object.player1
        @object.loser = @object.player2
      end
    end

    if @object.update_attributes(get_request_as_json params, :game)

      respond_to do |format|
        format.html  {redirect_to @object}
        format.json  { render :json => @object }
      end

    else
      respond_to do |format|
        format.html  {render 'edit'}
        format.json  { render :json => {:result => "Error"} }
      end
    end
  end

  def index

    @objects = Game.all

    respond_to do |format|
      format.html  #normal flow
      format.json  {render :json => @objects }
    end
  end

  def destroy
    object = Game.find(params[:id])

    object.destroy

    respond_to do |format|
      format.html  {redirect_to games_path, :flash => {:success => "Object Deleted"}}
      format.json  {render :json => {:result => "success"}}
    end
  end

  def winner

    user = User.find(params[:user_id])
    @object = Game.find(params[:game_id])

    if(!@object.winner)
    @object.winner = user
      if @object.winner == @object.player1
        @object.loser = @object.player2
      end

    end

    respond_to do |format|
      format.html  {render :show}
      format.json  { render :json => @object}
    end

  end

end

app/views/games/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>

<h3>Player 1</h3>
<div class="form-group">
  <%= f.select(:player1_id, options_from_collection_for_select(@users, :id, :name )) %>
</div>

<h2>VS</h2>

<h3>Player 2</h3>
<div class="form-group">
  <%= f.select(:player2_id, options_from_collection_for_select(@users, :id, :name )) %>
</div>


<h3>Winner</h3>
<div class="form-group">
  <%= f.select(:winner_id, options_from_collection_for_select(@players, :id, :name ),:include_blank => true) %>
</div>

app/views/games/_object.html.erb
<li>
	 <%= link_to object.name, object %>
     <strong>Winner: </strong><%= object.winner_name%>
</li>

app/views/games/edit.html.erb
<h1>Edit Game</h1>

<%= form_for(@object) do |f| %>
                            
<!-- the argument :f below is to pass the f into the partial -->
<%= render 'fields', :f => f%>

<div class="actions">
  <%= f.submit "Update", :class => "btn btn-primary"%>
</div>

<% end %>

</div>

app/views/games/index.html.erb
<h1>All</h1>

<%if current_user and current_user.admin %>
  <%= link_to "Add New", new_game_path %>
<% end %>
      

<ul class="index">

  <% @objects.each do |object| %>
      <%=render 'object', :object => object %>
  <%end%>

</ul> 

app/views/games/new.html.erb
<h1>New Game</h1>

<%= form_for(@object) do |f| %>

<%= render 'fields', :f => f %>  

<div class="actions">
  <%= f.submit "Create", :class => "btn btn-primary"%>
</div>

<% end %>

app/views/games/show.html.erb
  <div>
    <% if current_user and current_user.admin %>
         <%= link_to "Edit", edit_game_path(@object) %>

        <% if current_user and current_user.admin? %>
            | <%= link_to "delete", @object, :method => :delete, :data => { :confirm => "Are you sure?"},
                          :title => "Delete #{@object.name}"%>
        <%end%>
    <% end %>

    <h3><strong><%= @object.name%></strong></h3>
    <p><%= @object.created_at %></p>
    <h4><strong>Winner: </strong><%= @object.winner_name%></h4>

  </div>